### ISSUE TITLE
Panning from left edge in navigation link destination does not navigate back

### ISSUE THREAD

**Issue by palle-k** [nerdsupremacist/FancyScrollView#2]
When FancyScrollView is used in a view that is reached through a NavigationLink, it is not possible to pan from the left screen edge to navigate back.

Minimal example:

```swift
import SwiftUI
import FancyScrollView

struct ContentView: View {
    var body: some View {
        NavigationView {
            NavigationLink("Foo", destination: ChildView())
        }
    }
}

struct ChildView: View {
    var body: some View {
        FancyScrollView {
            Text("Bar")
        }
    }
}
```

Steps to reproduce:
1. Open the app
2. Tap on "Foo" to navigate to the ChildView
3. Place finger on left side of screen and swipe right to navigate back

Version information:
FancyScrollView 0.1.2
iOS 13.6 (17G5045c)

**Comment by nerdsupremacist** [comment]
This is a known issue due to the fact that `.setNavigationBarHidden` will disable the gesture recognizer.

A possible solution is to swizzle the implementation of `UINavigationController.setNavigationBarHidden(_:animated:)` to only change the alpha values of the bar instead of this whole weird logic. But that resulted in a lot of the calculations being wrong due to the safe area, so I still have to look at that.

**Comment by palle-k** [comment]
I have experimented a bit and I have a potential fix ready [here](https://github.com/palle-k/FancyScrollView/tree/develop), which builds upon your `hackNavigationToAllowSwipeBackWhenHidden` implementation.

I have tested it somewhat and it seems to behave well. But my testing hasn't been very thorough. 
I can create a pull request, but note that this also contains the changes from my pull request #3.

**Comment by nerdsupremacist** [comment]
Hihi I had no idea I pushed the `hackNavigationToAllowSwipeBackWhenHidden` 😅 

#3 is merged already, so don't hesitate to send the PR

**Comment by palle-k** [comment]
PR #4  is open :)

**Comment by nerdsupremacist** [comment]
Merged

**Comment by palle-k** [comment]
Looks like my fix no longer works in iOS 14 💩

**Comment by nerdsupremacist** [comment]
Let's wait to see if iOS 14 fixes this again
